### ISSUE TITLE
Version Number?

### ISSUE THREAD

**Issue by Adurol** [KaOS-Community-Packages/waifu#2]
Is it possible to update the PKGBUILD with a version number?

I a user installed the Waifu once, he won't get the newest version, cause he has the "latest" (will not be displayed as outdated).
I found [0.2b](https://bitbucket.org/pelana/waifu/src/273fce6b6dad8fb25361b8bb87ba566aeb6bbc71/app/js/main.js?at=master&fileviewer=file-view-default#main.js-21). If a version number is not the best solution, maybe a revision-number will do?

**Comment by demmm** [comment]
"latest" is not an acceptible way for pkgver, a proper version needs to be set.

**Comment by Gabrielgtx** [comment]
added 1.0 version
